exports.Action = {
  InitLegacy: 'init',
  Handshake: 'hs',
  QueryFetch: 'qf',
  QuerySubscribe: 'qs',
  QueryUnsubscribe: 'qu',
  QueryReply: 'q',
  BulkFetch: 'bf',
  BulkSubscribe: 'bs',
  BulkUnsubscribe: 'bu',
  Fetch: 'f',
  Subscribe: 's',
  Unsubscribe: 'u',
  Op: 'op',
  SnapshotFetch: 'nf',
  SnapshotFetchByTimestamp: 'nt',
  Presence: 'p',
  PresenceSubscribe: 'ps',
  PresenceUnsubscribe: 'pu',
  PresenceRequest: 'pr'
};
