var Backend = require('./backend');
module.exports = Backend;

Backend.Agent = require('./agent');
Backend.Backend = Backend;
Backend.DB = require('./db');
Backend.Error = require('./error');
Backend.logger = require('./logger');
Backend.MemoryDB = require('./db/memory');
Backend.MemoryMilestoneDB = require('./milestone-db/memory');
Backend.MemoryPubSub = require('./pubsub/memory');
Backend.MESSAGE_ACTIONS = require('./message-actions').ACTIONS;
Backend.MilestoneDB = require('./milestone-db');
Backend.ot = require('./ot');
Backend.projections = require('./projections');
Backend.PubSub = require('./pubsub');
Backend.QueryEmitter = require('./query-emitter');
Backend.SubmitRequest = require('./submit-request');
Backend.types = require('./types');
